//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzedaneWebMVC.SprzedaneReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Przedmioty", Namespace="http://schemas.datacontract.org/2004/07/Sprzedane")]
    [System.SerializableAttribute()]
    public partial class Przedmioty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataZakonczeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WygrywajacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WystawiajacyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataZakonczenia {
            get {
                return this.DataZakonczeniaField;
            }
            set {
                if ((this.DataZakonczeniaField.Equals(value) != true)) {
                    this.DataZakonczeniaField = value;
                    this.RaisePropertyChanged("DataZakonczenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kategoria {
            get {
                return this.KategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.KategoriaField, value) != true)) {
                    this.KategoriaField = value;
                    this.RaisePropertyChanged("Kategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wygrywajacy {
            get {
                return this.WygrywajacyField;
            }
            set {
                if ((object.ReferenceEquals(this.WygrywajacyField, value) != true)) {
                    this.WygrywajacyField = value;
                    this.RaisePropertyChanged("Wygrywajacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wystawiajacy {
            get {
                return this.WystawiajacyField;
            }
            set {
                if ((object.ReferenceEquals(this.WystawiajacyField, value) != true)) {
                    this.WystawiajacyField = value;
                    this.RaisePropertyChanged("Wystawiajacy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SprzedaneReference.ISprzedaneService")]
    public interface ISprzedaneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/GetPrzedmioty", ReplyAction="http://tempuri.org/ISprzedaneService/GetPrzedmiotyResponse")]
        SprzedaneWebMVC.SprzedaneReference.Przedmioty[] GetPrzedmioty(string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/GetPrzedmioty", ReplyAction="http://tempuri.org/ISprzedaneService/GetPrzedmiotyResponse")]
        System.Threading.Tasks.Task<SprzedaneWebMVC.SprzedaneReference.Przedmioty[]> GetPrzedmiotyAsync(string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/GetAllPrzedmioty", ReplyAction="http://tempuri.org/ISprzedaneService/GetAllPrzedmiotyResponse")]
        SprzedaneWebMVC.SprzedaneReference.Przedmioty[] GetAllPrzedmioty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/GetAllPrzedmioty", ReplyAction="http://tempuri.org/ISprzedaneService/GetAllPrzedmiotyResponse")]
        System.Threading.Tasks.Task<SprzedaneWebMVC.SprzedaneReference.Przedmioty[]> GetAllPrzedmiotyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/AddPrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/AddPrzedmiotResponse")]
        void AddPrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/AddPrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/AddPrzedmiotResponse")]
        System.Threading.Tasks.Task AddPrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/DeletePrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/DeletePrzedmiotResponse")]
        void DeletePrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/DeletePrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/DeletePrzedmiotResponse")]
        System.Threading.Tasks.Task DeletePrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/EditPrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/EditPrzedmiotResponse")]
        void EditPrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISprzedaneService/EditPrzedmiot", ReplyAction="http://tempuri.org/ISprzedaneService/EditPrzedmiotResponse")]
        System.Threading.Tasks.Task EditPrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISprzedaneServiceChannel : SprzedaneWebMVC.SprzedaneReference.ISprzedaneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SprzedaneServiceClient : System.ServiceModel.ClientBase<SprzedaneWebMVC.SprzedaneReference.ISprzedaneService>, SprzedaneWebMVC.SprzedaneReference.ISprzedaneService {
        
        public SprzedaneServiceClient() {
        }
        
        public SprzedaneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SprzedaneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SprzedaneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SprzedaneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SprzedaneWebMVC.SprzedaneReference.Przedmioty[] GetPrzedmioty(string term) {
            return base.Channel.GetPrzedmioty(term);
        }
        
        public System.Threading.Tasks.Task<SprzedaneWebMVC.SprzedaneReference.Przedmioty[]> GetPrzedmiotyAsync(string term) {
            return base.Channel.GetPrzedmiotyAsync(term);
        }
        
        public SprzedaneWebMVC.SprzedaneReference.Przedmioty[] GetAllPrzedmioty() {
            return base.Channel.GetAllPrzedmioty();
        }
        
        public System.Threading.Tasks.Task<SprzedaneWebMVC.SprzedaneReference.Przedmioty[]> GetAllPrzedmiotyAsync() {
            return base.Channel.GetAllPrzedmiotyAsync();
        }
        
        public void AddPrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            base.Channel.AddPrzedmiot(p);
        }
        
        public System.Threading.Tasks.Task AddPrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            return base.Channel.AddPrzedmiotAsync(p);
        }
        
        public void DeletePrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            base.Channel.DeletePrzedmiot(p);
        }
        
        public System.Threading.Tasks.Task DeletePrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            return base.Channel.DeletePrzedmiotAsync(p);
        }
        
        public void EditPrzedmiot(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            base.Channel.EditPrzedmiot(p);
        }
        
        public System.Threading.Tasks.Task EditPrzedmiotAsync(SprzedaneWebMVC.SprzedaneReference.Przedmioty p) {
            return base.Channel.EditPrzedmiotAsync(p);
        }
    }
}
